home/urls.py
from django.urls import path

from . import views

app_name= 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

questions/urls.py
from django.urls import path

from . import views

app_name= 'questions'
urlpatterns = [
    path('index', views.index, name='index'),
    path('add', views.add, name='add'),
    path('add/single', views.add_singlequestion, name='add_singlequestion'),
    path('add/multipart', views.add_multipartquestion, name='add_multipartquestion'),
    path('search_category', views.search_category, name='search_category'),
]

worksheetmate/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('questions/', include('questions.urls')),
    path('worksheets/', include('worksheets.urls')),
]

questions/models.py
from django.db import models
from django.utils.html import format_html_join

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=254)
    def __str__(self):
        return self.name + " (" + str(self.pk) + ")"

class Tag(models.Model):
    name = models.CharField(max_length=254)
    def __str__(self):
        return self.name + " (" + str(self.pk) + ")"
#    def question_list(self):
#        return self.question_set.all()

class Source(models.Model):
    name = models.CharField(max_length=254)
    description = models.CharField(max_length=254)
    def __str__(self):
        return self.name + " (" + str(self.pk) + ")"

class Block(models.Model):
    text = models.TextField()
    def __str__(self):
        return self.text + " (" + str(self.pk) + ")"
    def panelbody(self):
        return None
    def is_question(self):
        return hasattr(self, 'question')
    def is_singlequestion(self):
        return hasattr(self, 'question') and hasattr(self.question, 'singlequestion')
    def is_multipartquestion(self):
        return hasattr(self, 'question') and hasattr(self.question, 'multipartquestion')
    def is_worksheetformatblock(self):
        return hasattr(self, 'worksheetformatblock');
    def is_directionsblock(self):
        return hasattr(self, 'worksheetformatblock') and hasattr(self.worksheetformatblock, 'wfbdirections')

class Question(Block):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    date_created = models.DateTimeField(auto_now_add = True)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)

class SingleQuestion(Question):
    answer = models.TextField()
    def panelbody(self):
        return """ <table class="table-condensed">
            <tr>
            <th>Answer:</th>
            <td>""" + self.answer + """</td>
            </tr>
            <tr>
            <th>Spacing:</th>
            <td>""" + self.spacing + """</td>
            </tr>
            </table>
            """

class MultipartQuestion(Question):
    def list_of_parts(self):
        return '; '.join((qp.text for qp in self.questionpart_set.all())
        )
        # returnString = ""
        # for index, qp in enumerate(self.questionpart_set.all()):
        #     returnString += chr(index + 97) + ") " + qp.text + "<br />"
        # return format_html(returnString)
    def panelbody(self):
        return """ <table class="table-condensed">
            {% for qp in q.multipartquestion.questionpart_set.all|dictsort:"part_order" %}
            <tr>
            <th>{{ forloop.counter|alph }})</th>
            <th>Answer:</th>
            <td>{{ qp.answer }}</td>
            </tr>
            <tr>
            <td></td>
            <th>Spacing:</th>
            <td>{{ qp.spacing }}</td>
            </tr>
            {% endfor %}
            </table>
            """

class QuestionPart(models.Model):
    question = models.ForeignKey(MultipartQuestion, on_delete=models.CASCADE)
    text = models.TextField()
    part_order = models.IntegerField()
    answer = models.TextField()
    num_per_row = models.IntegerField(default=1)
    stretch_factor = models.FloatField(default=1.0)
    def __str__(self):
        return self.text + " (" + str(self.pk) + ")"

worksheets/models.py
from django.db import models

from django.db.models.signals import m2m_changed, pre_save
from django.dispatch import receiver

from questions.models import Block, Question

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=254)
    number = models.CharField(max_length=3)
    def __str__(self):
        return self.name

class Worksheet(models.Model):
    name = models.CharField(max_length=254)
    description = models.CharField(max_length=254, blank=True, null=True)
    date = models.DateField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    blocks = models.ManyToManyField(Block, blank=True)
    block_order = models.CharField(max_length=254, blank=True)
    def __str__(self):
        return self.name
    def get_split_block_order(self):
        return self.block_order.split(';')
    def set_block_order(self, block_pks):
        self.block_order = ';'.join(str(bpk) for bpk in block_pks)
    def add_block_to_order(self, block_pk):
        if self.block_order == '': #if this is the first element being added...
            self.block_order = str(block_pk) #don't include the leading semicolon
        else:
            self.block_order += ";" + str(block_pk)
    def add_block_to_order_after(self, block_pk, index):
        order = self.get_split_block_order()
        order.insert(index + 1, block_pk)
        self.set_block_order(order)
    def remove_block_from_order(self, block_index):
        order = self.get_split_block_order()
        order.pop(block_index)
        self.set_block_order(order)
    # def swap_block_orders(self, block_pk1, block_pk2):
    #     order = self.get_split_block_order()
    #     index1 = order.index(str(block_pk1))
    #     index2 = order.index(str(block_pk2))
    #     order[index1], order[index2] = order[index2], order[index1]
    #     self.set_block_order(order)
    def swap_with_previous(self, block_index):
        order = self.get_split_block_order()
        order[block_index-1], order[block_index] = order[block_index], order[block_index-1]
        self.set_block_order(order)
    def swap_with_next(self, block_index):
        order = self.get_split_block_order()
        order[block_index], order[block_index+1] = order[block_index+1], order[block_index]
        self.set_block_order(order)
    def swap_after(self, block_index, new_index):
        order = self.get_split_block_order()
        block_pk = order.pop(block_index)
        order.insert(new_index + 1, block_pk)
        self.set_block_order(order)
    def blocks_in_order(self):
        order = self.get_split_block_order()
        blocks = []
        for bpk in order:
            blocks += [self.blocks.get(pk=int(bpk))]
        return blocks
    def questions_in_order(self):
        if self.block_order == '': #if list completely empty, return None
            return None
        order = self.get_split_block_order()
        questions = []
        for bpk in order:
            block = self.blocks.get(pk=int(bpk))
            if block.is_question():
                questions += [block.question]
        return questions

class WorksheetFormatBlock(Block):
    latex_code = models.TextField(blank = True, null = True)
    def __str__(self):
        return self.text

class WFBDirections(WorksheetFormatBlock):
    directions = models.TextField()
    def __str__(self):
        return self.directions
    #def set_directions(self):
    #    self.latex_code = r'\end{questions}' + "\n\n" + str(directions) + "\n\n" + r'\begin{questions}'

#this updates the block_order list every time either questions.add or questions.remove is called (i.e., you can use the built-in Django functions and still have the list update)
@receiver(m2m_changed, sender=Worksheet.blocks.through)
def blocks_changed(sender, **kwargs):
    instance = kwargs.pop('instance', None)
    action = kwargs.pop('action', None)
    pk_set = kwargs.pop('pk_set', None)
    if action == 'pre_add':
        for block_pk in pk_set:
            instance.add_block_to_order(block_pk)
    # elif action == 'pre_remove':
    #     for block_pk in pk_set:
    #         instance.remove_block_from_order(block_pk)
    instance.save()

#this updates the direction block's latex_code on save
@receiver(pre_save, sender=WFBDirections)
def directions_changed(sender, **kwargs):
    instance = kwargs.pop('instance', None)
    instance.text ='Directions'
    instance.latex_code = r'\ifthenelse{\boolean{inquestionsenv}}{\end{questions}' + "\n\n" + str(instance.directions) + "\n\n" + r'\begin{questions}}{' + str(instance.directions) + r'}'

questions/forms.py
from django import forms
from django.forms import modelform_factory, modelformset_factory

from .models import *
from worksheets.models import Worksheet

class QuestionForm(forms.Form):
    choices = forms.ModelMultipleChoiceField(
        queryset = Question.objects.all(),
        widget = forms.CheckboxSelectMultiple,
    )
    worksheet = forms.ModelChoiceField(
        queryset = Worksheet.objects.all(),
        empty_label = "Select a worksheet...",
    )

class SearchQuestionsForm(forms.Form):
    search_text = forms.CharField(required=False, label="")

class AddQuestionForm(forms.Form):
    choice = forms.ChoiceField(choices=[('SingleQuestion', 'Single Question'),('MultipartQuestion', 'Multipart Question')], widget=forms.RadioSelect)

AddSingleQuestionForm = modelform_factory(SingleQuestion, fields='__all__') #<--- work on this, then use formsets for the multipartquestion

AddMultipartQuestionForm = modelform_factory(MultipartQuestion, fields='__all__')
AddPartFormset = modelformset_factory(QuestionPart, exclude=("question", "part_order",))

questions/views.py
import subprocess
import os
import time

from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.db.models.query import QuerySet

from .models import *
from .forms import *
# Create your views here.
def index(request):
    if request.method == 'GET':
        search_form = SearchQuestionsForm(request.GET)
        if search_form.is_valid() and search_form.cleaned_data['search_text'] != '':
            search_text = search_form.cleaned_data['search_text']
            if search_text == 'unused': #special search term used to find unused questions
                question_list = Question.objects.filter(worksheet = None)
            else:
                question_list = Question.objects.filter(category__name__icontains=search_text) | Question.objects.filter(tags__name__icontains=search_text) | Question.objects.filter(worksheet__name__icontains=search_text) #The | represents set union
            question_list = question_list.distinct().order_by("-category") #remove duplicate search results and order them
        else:
            question_list = Question.objects.all().order_by("-category")
    else:
        question_list = Question.objects.all().order_by("-category")

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            choice_set = form.cleaned_data['choices'].all()
            worksheet = form.cleaned_data['worksheet']
            for choice in choice_set:
                worksheet.blocks.add(choice)
            messages.success(request, "Question added to " + worksheet.name)
        else:
            messages.error(request, "Something went wrong.")
    else:
        form = QuestionForm()

    search_form = SearchQuestionsForm()
    search_form_placeholder = request.GET.get('search_text', 'Search')
    if search_form_placeholder == '':
        search_form_placeholder = 'Search'
    search_form.fields['search_text'].widget.attrs["placeholder"] = search_form_placeholder
    context = {
        'question_list': question_list,
        'form': form,
        'search_form': search_form,
        }
    return render(request, 'questions/list_of_questions.html', context)

def add(request):
    if request.method == 'POST':
        form = AddQuestionForm(request.POST)
        if form.is_valid():
            choice = form.cleaned_data['choice']
            new_request = HttpRequest() #need to pass a new request so old POST data doesn't go through
            if choice == 'SingleQuestion':
                new_request = HttpRequest()
                return add_singlequestion(new_request)
            else:
                return add_multipartquestion(new_request)

    context = {
        'form': AddQuestionForm(),
        'formset': None,
        'form_action': 'add',
    }
    return render(request, 'questions/add_question.html', context)

def add_singlequestion(request):
    if request.method == 'POST':
        form = AddSingleQuestionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New question added.")
        else:
            messages.error(request, "Something went wrong.")

        new_request = HttpRequest()
        return add(new_request)

    context = {
        'form': AddSingleQuestionForm(),
        'formset': None,
        'form_action': 'add/single',
    }
    return render(request, 'questions/add_question.html', context)

def add_multipartquestion(request):
    if request.method == 'POST':
        form = AddMultipartQuestionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New question added.")
        else:
            messages.error(request, "Something went wrong.")

        new_request = HttpRequest()
        return add(new_request)

    form = AddMultipartQuestionForm()
    formset = AddPartFormset(queryset=QuestionPart.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'questions/add_question.html', context)

def search_category(request):
    if request.method == "GET":
        search_text = request.GET['search_text']
        if search_text is not None and search_text != u"":
            search_text = request.GET['search_text']
            catsearch = Question.objects.filter(category__contains = search_text)
        else:
            catsearch = []

        return render(request, 'ajax_search.html', {'catsearch': catsearch})

questions/templates/questions/add_question.html
{% extends "base.html" %}

{% load static %}

{% load questions_extras %}

{% block title %}Add New Question{% endblock %}

{% block worksheets_nav %}active{% endblock %}

{% block content %}
  <form action="{{ form_action }}" method="post">
    {% csrf_token %}
    <h4>Question</h4>
    <table class="table-condensed">
      {{ form.as_table }}
    </table>
      {% if formset %}
        {% for formpart in formset %}
          <h4>Part {{ forloop.counter|alph }})</h4>
          <table class="table-condensed">
            {{ formset.as_table }}
          </table>
        {% endfor %}
      {% endif %}
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

questions/templates/questions/ajax_search.html
<script>
$(function() {

    $('#search').keyup(function() {

        $.ajax({
            type: "GET",
            url: "/questions/search_category/",
            data: {
                'search_text' : $('#search').val(),
                'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
            },
            success: searchSuccess,
            dataType: 'html'
        });
    });
});

function searchSuccess(data, textStatus, jqXHR)
{
    $('#search-results').html(data)
}
</script>

{% if catsearch > 0 %}
    <ul class="catsearch">
        {% for cat in catsearch %}
            <li>
                <p>{{ cat }}</p>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No status found.</p>
{% endif %}

questions/templates/questions/block_panelbody.html
<div class="panel-body">
  {% if b.is_singlequestion or b.is_multipartquestion %}
    {% include "questions/question_panelbody.html" with q=b.question %}
  {% elif b.is_worksheetformatblock %}
    {% if b.is_directionsblock %}
      {{ b.worksheetformatblock.wfbdirections.directions }}
    {% else %}
      <i>Worksheet Format Block</i>
    {% endif %}
  {% endif %}
</div>

questions/templates/questions/list_of_questions.html
{% extends "base.html" %}

{% load static %}

{% load questions_extras %}

{% block title %}List of Questions{% endblock %}

{% block questions_nav %}active{% endblock %}

{% block navbar_right %}<form class="navbar-form navbar-right" role="search" action="index" method="get"><div class="form-group">{{ search_form }}</div> <button type="submit" class="btn btn-primary btn-sm" ><span class="glyphicon glyphicon-search"></span> Search</button></form>{% endblock %}

{% block content %}
  <p>{{ question_list|length }} results</p>
  {% if question_list %}
    <form action="index" method="post">
      {% csrf_token %}
      <div class="panel-group" id="accordion">
        {% for q in question_list %}
          <div class="panel panel-default">
            <div class="panel-heading clearfix" style="background-color:{% cycle '#FCF3F3' '#FCFCFC' %}">
              <input class="form-check-input" type="checkbox" name="choices" value="{{ q.id }}">&emsp;<span class="panel-title" style="width: 75%;"><a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}" style="text-decoration: none; white-space: pre-wrap;">{{ q.text }}</a></span>
              {% if q.worksheet_set.all %}
              <span class="pull-right"><b>Used in:</b>
              {% for ws in q.worksheet_set.all %}
                <a href="/worksheets/edit/{{ ws.pk }}">{{ ws.name }}</a>&emsp;
              {% endfor %}</span>
              {% endif %}
              {% if q.multipartquestion %}
                <br />
                {% for qp in q.multipartquestion.questionpart_set.all|dictsort:"part_order" %}
                  &emsp;&emsp;&emsp;{{ forloop.counter|alph }})&ensp;{{ qp.text }}<br />
                {% endfor %}
              {% endif %}
            </div>
            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
              {% include "questions/question_panelbody.html" %}
            </div>
          </div>
        {% endfor %}
      </div>
      {{ form.worksheet }}
      <input type="submit" class="btn btn-primary btn-sm" value="Add to Worksheet" />
    </form>
  {% else %}
    No questions match your query.
  {% endif %}
{% endblock %}

questions/templates/questions/multipartquestion_panelbody.html
{% load questions_extras %}

<table class="table-condensed">
{% for qp in q.multipartquestion.questionpart_set.all|dictsort:"part_order" %}
  <tr>
    <th>{{ forloop.counter|alph }})</th>
    <th>Answer:</th>
    <td></td>
  </tr>
  <tr>
    <th></th>
    <th></th>
    <td>{{ qp.answer }}</td>
  </tr>
  <tr>
    <td></td>
    <th>Number per row:</th>
    <td>{{ qp.num_per_row }}</td>
{% endfor %}
</table>

questions/templates/questions/question_panelbody.html
{% if q.tags.all %}
  <h4>Tags: <small>{% if q.category %}<b>{{ q.category.name }}</b>&emsp;{% endif %}{% for t in q.tags.all %}{{ t.name }}&emsp;{% endfor %}</small></h4>
{% endif %}
{% if q.singlequestion %}
  {% include "questions/singlequestion_panelbody.html" %}
{% elif q.multipartquestion %}
  {% include "questions/multipartquestion_panelbody.html" %}
{% endif %}

questions/templates/questions/singlequestion_panelbody.html
<table class="table-condensed">
  <tr>
    <th>Answer:</th><td></td>
  </tr>
  <tr>
    <td></td><td>{{ q.singlequestion.answer }}</td>
  </tr>
</table>